### ISSUE TITLE
Consider what app should do when Advance Sheet is requested when animal detected.

### ISSUE THREAD

**Issue by akshayvernekar** [akshayvernekar/Brilliant_pad_issue_management#11]
:: animal entered and animal left messages displayed unpredictably

:: consider what do when user presses “Advance Sheet” and there is detection 
:: consider what do when user presses “Advance Sheet” and out of paper
:: consider what do when user presses “Advance Sheet” and motor overcorrect
:: consider what do when user presses “Advance Sheet” and machine offline
:: what other situations can you think of — like machine is updating firmware, etc.

**Comment by akshayvernekar** [comment]
>  consider what do when user presses “Advance Sheet” and there is detection

We were not handling this situation . We will not advance sheet when animal is on the pad and report a "DEVICE_BUSY" error.

> consider what do when user presses “Advance Sheet” and out of paper

we send "END_OF_PAPER" error to the server.

> consider what do when user presses “Advance Sheet” and motor overcorrect

We are sending "MOTOR_OVER_CURRENT" error.

> consider what do when user presses “Advance Sheet” and machine offline

Advance command is lost if the device is offline, App needs to show appropriate status of the device. 

> what other situations can you think of — like machine is updating firmware, etc.

When updating firmware MQTT is down so no command gets sent to the device. App needs to show some message that device is updating firmware and prevent user from pressing any buttons on the app.

**Comment by alanjcook** [comment]
Please review this with Praveena  we discussed this earlier today.

**Comment by akshayvernekar** [comment]
Closing this issue as it is duplicate of issue : https://github.com/akshayvernekar/Brilliant_pad_issue_management/issues/17
