### ISSUE TITLE
APP/Machine Behavior: Advance Sheet

### ISSUE THREAD

**Issue by alanjcook** [akshayvernekar/Brilliant_pad_issue_management#17]
What does app display when user requests Advance Sheet?

How does machine behave when:

a) machine indicates detection
b) persistent blockage
c) error condition
d) offline

**Comment by akshayvernekar** [comment]
> a) machine indicates detection

Machine advances sheet. This behavior will be changed, we will send an Error code.

> b) persistent blockage

Machine advances sheet.This behavior will be changed, we will send an Error code.

> c) error condition

machine sends error code.

> d) offline

Command is lost, app needs to disable the buttons when device is offline, app/server can know the status of the device .

**Comment by alanjcook** [comment]
I spoke to Praveena about this today. Please review with him and confirm what he needs to create the functionality we discussed together.

**Comment by akshayvernekar** [comment]
@cumulations  we are now sending a new error "AnimalPresent" error in case of 
a) machine indicates detection
b) persistent blockage
Please handle accordingly. Check the mqtt doc for more details

**Comment by alanjcook** [comment]
Akshay: Do you indicate the same AnimalPresent error for (a) detection and (b) persistent blockage? Or is there a different error? 

Praveena: Please confirm how APP will behave when it receives these error(s).

**Comment by akshayvernekar** [comment]
Same error for both cases in case advance pad is sent .

**Comment by cumulations** [comment]
@alanjcook  when the error comes, we will show the device in error state with clear error command available to the user.
would that be ok ?

**Comment by alanjcook** [comment]
I think that will work, but we need to distinguish in the app between animal detection and persistent detection.

**Comment by cumulations** [comment]
@alanjcook  There will be a description of the error state the device is in. There we could clearly mention like there seems to be something blocking our sensors for a long time or something like that
