### ISSUE TITLE
Duplicate Animal Entry and Exit issue

### ISSUE THREAD

**Issue by cumulations** [akshayvernekar/Brilliant_pad_issue_management#26]
We were actually able to reproduce this issue consistently in the below scenarios.

1.  Issue 5 look-in commands from App in quick succession 
2. Trigger an Animal Detection 
3. Wait till you get the Animal Left
4. Trigger the Animal Detection again >> At this point, you will see multiple Animal Entry.

**Comment by cumulations** [comment]
Go To PK Device and click on logs for October 1st and look from 4:26 PM

**Comment by alanjcook** [comment]
Also take note of the DOG WAIT TIME interval, which says if the dog returns to the machine before the interval expires then don't count this as a new dog visit. Is this re-entry being communicated to the server? Still would not explain lack of Animal Entry // Dog Left events in the log.

**Comment by cumulations** [comment]
Dog wait time was set to 13 seconds in our settings.

**Comment by alanjcook** [comment]
Is this the thread that captures ANIMAL ENTRY shows up in log several times before ANIMAL EXIT? If so, when animal re-enters during DOG WAIT TIME, how is this handled on APP and in Cloud? Have we confirmed APP is working properly?
