### ISSUE TITLE
1.0.3:  User sends Paper Advance command when machine indicates detection. Machine response is not not consistent. 

### ISSUE THREAD

**Issue by akshayvernekar** [akshayvernekar/Brilliant_pad_issue_management#9]

**Comment by akshayvernekar** [comment]
No changes were made with regard to MQTT or any other wifi settings from 102 to 103 , from my testing as well as from Alan's testing from 24 Sept the issues seems to be after wifi configuration if the app is not restarted . I will also see if there is an issue with upload speed after wifi configuration .

**Comment by alanjcook** [comment]
I noticed this again with Laura’s machine yesterday. What is supposed to happen after the persistant detection?

**Comment by akshayvernekar** [comment]
In 103, if there is "persistent detection" and advance pad command is sent , the pad will advance . 
in future firmware we will report error to app/server in case a command is sent when animal is on the pad.

**Comment by akshayvernekar** [comment]
Duplicate of issue https://github.com/akshayvernekar/Brilliant_pad_issue_management/issues/17
